### ISSUE TITLE
i2c mutex module not installed during installation from GitHub

### ISSUE THREAD

**Issue by jharris1993** [DexterInd/GoPiGo3#338]
Using either installation method, (Quick install, including sensors or the manual install method), attempting to run something using easygopigo returns the following errors:

```
Python 3.7.3 (/usr/bin/python3)
>>> %Run test_servos.py
Traceback (most recent call last):
  File "/home/pi/Desktop/test_servos.py", line 1, in <module>
    import easygopigo3 as easy
  File "/usr/local/lib/python3.7/dist-packages/gopigo3-1.3.2.1-py3.7.egg/easygopigo3.py", line 13, in <module>
    import easysensors
  File "/usr/local/lib/python3.7/dist-packages/gopigo3-1.3.2.1-py3.7.egg/easysensors.py", line 1, in <module>
    from I2C_mutex import Mutex
ModuleNotFoundError: No module named 'I2C_mutex'
>>> 
```

How do I install this module?
Can it be included in the standard install process?

**Comment by slowrunner** [comment]
> Installation target: Generic Buster image install from Raspberry Pi installation sources.

Is this issue with installing GoPiGo3 software over the [2023-05-03 32-bit Buster](https://downloads.raspberrypi.com/raspios_oldstable_armhf/images/raspios_oldstable_armhf-2023-05-03/) archive?

> Using .. Quick install, including sensors

Meaning execution of:
```
curl -kL dexterindustries.com/update_gopigo3 | bash
curl -kL dexterindustries.com/update_sensors | bash
```
from the https://github.com/DexterInd/GoPiGo3#quick-install documentation?

**Comment by CleoQc** [comment]
fixed with new Trixie installation
